# Generated by Django 3.2 on 2021-04-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(max_length=15)),
                ('cp', models.IntegerField(default=0)),
                ('trestbps', models.IntegerField(default=0)),
                ('chol', models.IntegerField(default=0)),
                ('fbs', models.BooleanField(default=False)),
                ('restecg', models.BooleanField(default=False)),
                ('thalach', models.IntegerField(default=0)),
                ('exang', models.BooleanField(default=False)),
                ('oldpeak', models.FloatField(default=0.0)),
                ('slope', models.IntegerField(default=0)),
                ('ca', models.BooleanField(default=False)),
                ('thal', models.IntegerField(default=0)),
                ('target', models.BooleanField()),
                ('percent_of_disease', models.CharField(max_length=11)),
            ],
        ),
    ]
