# Generated by Django 3.2 on 2021-04-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_values_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.person'),
        ),
    ]
