# Generated by Django 3.2 on 2021-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_values_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='sex',
            field=models.BooleanField(default=False),
        ),
    ]
