# Generated by Django 3.2 on 2021-04-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_values_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='values',
            name='percent_of_disease',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
